#!/usr/bin/env node
// Prebuild step. Reads the LLM usage guide from its canonical location and
// emits src/assets/embedded.generated.ts with its contents as a TS string
// constant. Both tsx (dev) and esbuild (prod) then consume it as a plain
// import — no special loaders or runtime fs reads.
//
//   LLM_GUIDE   apps/canary-browser/src/assets/llm-guide.txt
//
// (The daemon bundle + sandbox client are embedded by @usecanary/daemon-client.)
//
// Fails fast if any source is missing, with a hint for how to produce it.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, "..");
const assetsDir = resolve(pkgRoot, "src/assets");

mkdirSync(assetsDir, { recursive: true });

const sources = [
  {
    name: "LLM_GUIDE",
    path: resolve(assetsDir, "llm-guide.txt"),
    hint: "Restore the file at apps/canary-browser/src/assets/llm-guide.txt",
  },
];

const missing = sources.filter((s) => !existsSync(s.path));
if (missing.length > 0) {
  for (const m of missing) {
    process.stderr.write(`Missing required asset: ${m.path} (${m.hint})\n`);
  }
  process.exit(1);
}

const lines = [
  "// AUTO-GENERATED by scripts/embed-assets.mjs. DO NOT EDIT.",
  "// Source: src/assets/llm-guide.txt.",
  "// Regenerate by running `pnpm prebuild`.",
  "/* eslint-disable */",
  "",
];

for (const s of sources) {
  const text = readFileSync(s.path, "utf8");
  lines.push(`export const ${s.name}: string = ${JSON.stringify(text)};`);
}
lines.push("");

const out = resolve(assetsDir, "embedded.generated.ts");
const newContent = lines.join("\n");
let needsWrite = true;
if (existsSync(out)) {
  needsWrite = readFileSync(out, "utf8") !== newContent;
}
if (needsWrite) {
  writeFileSync(out, newContent);
}
