#!/usr/bin/env node
// Prebuild step. Reads four source files from their canonical locations and
// emits src/assets/embedded.generated.ts with their contents as TS string
// constants. Both tsx (dev) and esbuild (prod) then consume them as plain
// imports — no special loaders or runtime fs reads.
//
//   DAEMON_BUNDLE   apps/canary-daemon/dist/daemon.bundle.mjs
//   SANDBOX_CLIENT  apps/canary-daemon/dist/sandbox-client.js
//   LLM_GUIDE       apps/canary-browser/src/assets/llm-guide.txt
//   SKILL_MD        skills/canary/SKILL.md
//
// Fails fast if any source is missing, with a hint for how to produce it.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, "..");
const repoRoot = resolve(pkgRoot, "../..");
const daemonDist = resolve(repoRoot, "apps/canary-daemon/dist");
const assetsDir = resolve(pkgRoot, "src/assets");

mkdirSync(assetsDir, { recursive: true });

const sources = [
  {
    name: "DAEMON_BUNDLE",
    path: resolve(daemonDist, "daemon.bundle.mjs"),
    hint: "pnpm --filter @canary/daemon build",
  },
  {
    name: "SANDBOX_CLIENT",
    path: resolve(daemonDist, "sandbox-client.js"),
    hint: "pnpm --filter @canary/daemon build",
  },
  {
    name: "LLM_GUIDE",
    path: resolve(assetsDir, "llm-guide.txt"),
    hint: "Restore the file at apps/canary-browser/src/assets/llm-guide.txt",
  },
  {
    name: "SKILL_MD",
    path: resolve(repoRoot, "skills/canary/SKILL.md"),
    hint: "Restore the file at skills/canary/SKILL.md",
  },
];

const missing = sources.filter((s) => !existsSync(s.path));
if (missing.length > 0) {
  console.error("Error: required source files missing:");
  for (const m of missing) {
    console.error(`  - ${m.path}`);
    console.error(`      fix: ${m.hint}`);
  }
  process.exit(1);
}

const lines = [
  "// AUTO-GENERATED by scripts/embed-assets.mjs. DO NOT EDIT.",
  "// Sources: apps/canary-daemon/dist/, src/assets/llm-guide.txt,",
  "// skills/canary/SKILL.md. Regenerate by running `pnpm prebuild`.",
  "/* eslint-disable */",
  "",
];

for (const s of sources) {
  const text = readFileSync(s.path, "utf8");
  lines.push(`export const ${s.name}: string = ${JSON.stringify(text)};`);
}
lines.push("");

const out = resolve(assetsDir, "embedded.generated.ts");
const newContent = lines.join("\n");
let needsWrite = true;
if (existsSync(out)) {
  needsWrite = readFileSync(out, "utf8") !== newContent;
}
if (needsWrite) {
  writeFileSync(out, newContent);
  console.log(`Generated src/assets/embedded.generated.ts (${newContent.length} bytes)`);
}
