#!/usr/bin/env node
// Prebuild step. Reads the daemon's esbuild output from its canonical location
// and emits src/assets/embedded.generated.ts with the contents as TS string
// constants. Both tsx (dev) and esbuild (prod consumers) then consume them as
// plain imports — no special loaders or runtime fs reads.
//
//   DAEMON_BUNDLE   apps/canary-daemon/dist/daemon.bundle.mjs
//   SANDBOX_CLIENT  apps/canary-daemon/dist/sandbox-client.js
//
// (The LLM guide + skill markdown stay embedded in apps/canary-browser; this
// package owns only the daemon runtime artifacts.)
//
// Fails fast if any source is missing, with a hint for how to produce it.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, "..");
const repoRoot = resolve(pkgRoot, "../..");
const daemonDist = resolve(repoRoot, "apps/canary-daemon/dist");
const assetsDir = resolve(pkgRoot, "src/assets");

mkdirSync(assetsDir, { recursive: true });

const sources = [
  {
    name: "DAEMON_BUNDLE",
    path: resolve(daemonDist, "daemon.bundle.mjs"),
    hint: "pnpm --filter @usecanary/daemon build",
  },
  {
    name: "SANDBOX_CLIENT",
    path: resolve(daemonDist, "sandbox-client.js"),
    hint: "pnpm --filter @usecanary/daemon build",
  },
];

// Treat a present-but-empty file (e.g. from an interrupted/failed esbuild) as
// missing — embedding an empty bundle would produce a daemon that fails to
// start with an opaque error instead of failing fast here with a hint.
const missing = sources.filter((s) => {
  try {
    return !existsSync(s.path) || statSync(s.path).size === 0;
  } catch {
    return true;
  }
});
if (missing.length > 0) {
  for (const m of missing) {
    process.stderr.write(
      `Missing or empty required asset: ${m.path} (${m.hint})\n`
    );
  }
  process.exit(1);
}

const lines = [
  "// AUTO-GENERATED by scripts/embed-daemon.mjs. DO NOT EDIT.",
  "// Sources: apps/canary-daemon/dist/. Regenerate by running `pnpm prebuild`.",
  "/* eslint-disable */",
  "",
];

for (const s of sources) {
  const text = readFileSync(s.path, "utf8");
  lines.push(`export const ${s.name}: string = ${JSON.stringify(text)};`);
}
lines.push("");

const out = resolve(assetsDir, "embedded.generated.ts");
const newContent = lines.join("\n");
let needsWrite = true;
if (existsSync(out)) {
  needsWrite = readFileSync(out, "utf8") !== newContent;
}
if (needsWrite) {
  writeFileSync(out, newContent);
}
